mutation createAlbum($input: CreateAlbumInput!) {
  createAlbum(input: $input) {
    id
    title
    user {
      id
      name
    }
  }
}

query getUsers {
  users {
    data {
      id
      email
      username
    }
  }
}
