query getPhotosInfo($id: ID!, $options: PageQueryOptions) {
  album(id: $id) {
    id
    photos(options: $options) {
      data {
        id
        title
        thumbnailUrl
      }
    }
  }
}

query getAlbumInfo($id: ID!) {
  album(id: $id) {
    id
    title
    user {
      id
      name
      username
    }
  }
}
